version: "3"

networks:
  gitea:
    driver: bridge

volumes:
  gitea_data:
  gitea_db:

services:
  gitea:
    image: gitea/gitea:1.22.1
    container_name: gitea
    restart: always
    ports:
      - "3000:3000"
      - "222:22"
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=${GITEA__DB_TYPE}
      - GITEA__database__HOST=${GITEA__DB_HOST}
      - GITEA__database__NAME=${GITEA__DB_NAME}
      - GITEA__database__USER=${GITEA__DB_USER}
      - GITEA__database__PASSWD=${GITEA__DB_PASSWD}
    volumes:
      - gitea_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - gitea
    depends_on:
      - giteadb

  giteadb:
    image: mysql:8
    container_name: gitea-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - gitea_db:/var/lib/mysql
    networks:
      - gitea